### ISSUE TITLE
Unable to use angular2-multiselect-dropdown

### ISSUE THREAD

**Issue by umeshka** [toni-rmc/laravel-angular-integration#1]
Hi Toni,
I am getting below error then trying to add Dropdown.

![image](https://user-images.githubusercontent.com/22589628/29240447-2b5a3f86-7f83-11e7-880e-35de61a1baff.png)

![image](https://user-images.githubusercontent.com/22589628/29240452-5201f502-7f83-11e7-890b-759fa311b0ea.png)

Please let me know what wrong i am doing.

Thanks,
Umesh B. K

**Comment by toni-rmc** [comment]
When you did:

npm install angular2-multiselect-dropdown

npm installed it in node_modules directory.

I think you will need to dive into node_modules, find
angular2-multiselect-dropdown folder, and copy that entire folder into
public/Ng.

2017-08-12 13:56 GMT+02:00 umeshka <notifications@github.com>:

**Comment by toni-rmc** [comment]
This is quick and dirty solution I admit but in my next commit I'm
addressing that very issue of adding and managing external packages in your
Angular apps.

There will be two new helpful commands for that (adding and deleting).

README will be updated and I will notify you personally in an email.


2017-08-12 16:23 GMT+02:00 Toni Romic <toni.rmc@gmail.com>:

**Comment by umeshka** [comment]
Hi Toni,
Thanks for the reply.

I have tried as per the instruction, still i am getting error .

![image](https://user-images.githubusercontent.com/22589628/29274540-dac526ae-8125-11e7-952c-d10f0413d5f2.png)
 
My css & scss files are also not getting copied in public folder. (laravel blade and angular2 css)

**Comment by toni-rmc** [comment]
When you are importing new library you have to tell SystemJS where from to
load it.

In your case open: "angular_apps/config/app1.config.js"

You need to add mapping for your library.
Find comment

// other libraries

this is where you add new mappings.

Lines #32, #33, #34, #35 in your case should look like this

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api':
'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
      'angular2-multiselect-dropdown/angular2-multiselect-dropdown':
'npm:angular2-multiselect-dropdown/angular2-multiselect-dropdown.umd.js'

Last line is the one you will add.
This one:
'angular2-multiselect-dropdown/angular2-multiselect-dropdown': 'npm:angular2-multiselect-dropdown/angular2-multiselect-dropdown.umd.js'

Don't forget to separate lines with commas.

Publishing .scss files is not supported yet.

Not sure what you mean by "laravel blade" .css not copied.

.css files should be copied to public.
Only place files are published (copied) from is angular_apps folder, so if
you have .css file somewhere outside angular_apps folder you should not
expect it to be copied to public.




2017-08-14 15:56 GMT+02:00 umeshka <notifications@github.com>:

**Comment by toni-rmc** [comment]
After you edit "angular_apps/config/app1.config.js"
don't forget to run:

npm run ng-compile

otherwise changes won't take effect.


2017-08-14 19:52 GMT+02:00 Toni Romic <toni.rmc@gmail.com>:
