### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by umeshka** [toni-rmc/laravel-angular-integration#10]
![image](https://user-images.githubusercontent.com/22589628/40361553-5a62f564-5de7-11e8-89ae-aae41658da04.png)

1. How can i add spinner instead of Loading......
2. How can i speed up my loading.
3. Also i am getting error JS Loading.

Thanks and Regards,
Umesh B. K

**Comment by toni-rmc** [comment]
You should try to move your project to latest version which uses angular-cli and webpack bundling, it produces much faster applications.
