### ISSUE TITLE
Help on ERROR in multi script-loader!

### ISSUE THREAD

**Issue by umeshkatak** [toni-rmc/laravel-angular-integration#11]
Hi Toni,

I am getting below error, while using "npn run build". I am integrating AdminLte.

![image](https://user-images.githubusercontent.com/39160906/41421896-6762bb9c-7015-11e8-896f-8063637671ea.png)

**Comment by umeshkatak** [comment]
Hi Toni,
When i use npm run build i get above mention error. But if i use ng build it works file.  
below is my angular-cli.json Script &  Style code. if i remove the style & script links and run npm build command directory is created in Public folder. 
"styles": [
        "styles.css",
         "../node_modules/bootstrap/dist/css/bootstrap.css",
        "../node_modules/font-awesome/css/font-awesome.css",
        "../node_modules/ionicons/dist/css/ionicons.css",
        "_variables.less",
        "../node_modules/icheck/skins/flat/blue.css",
        "../node_modules/morris.js/morris.css",
        "../node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css",
        "../node_modules/admin-lte/plugins/daterangepicker/daterangepicker.css",
        "../node_modules/bootstrap3-wysihtml5-bower/dist/bootstrap3-wysihtml5.css"
      ],
      "scripts": [
      "../node_modules/jquery/dist/jquery.js",
        "../node_modules/jqueryui/jquery-ui.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js",
        "../node_modules/raphael/raphael.js",
        "../node_modules/morris.js/morris.js",
        "../node_modules/jquery-sparkline/jquery.sparkline.js",
        "../node_modules/jquery-knob/dist/jquery.knob.min.js",
        "../node_modules/moment/moment.js",
        "../node_modules/daterangepicker/daterangepicker.js",
        "../node_modules/bootstrap-datepicker/js/bootstrap-datepicker.js",
        "../node_modules/jquery-slimscroll/jquery.slimscroll.js",
        "../node_modules/bootstrap3-wysihtml5-bower/dist/bootstrap3-wysihtml5.all.js",
        "../node_modules/icheck/icheck.js",
        "../node_modules/admin-lte/dist/js/app.js",
        "assets/js/adminLTEOptions.js",
        "assets/js/scripts.js"
      ],

Thanks and Regards,
Umesh

**Comment by toni-rmc** [comment]
Check out documentation on how to include 3rd party scripts in Angular 5.
