### ISSUE TITLE
Can't access image for assets folder

### ISSUE THREAD

**Issue by umeshka** [toni-rmc/laravel-angular-integration#12]
Hi Toni,

Cannot assets folder image from asset folder. Below path work fine in ng-serve.
`<img _ngcontent-c0="" alt="No Image" class="img-rounded" src="assets/user2-160x160.jpg">`

But for public folder.
`<img _ngcontent-c0="" alt="No Image" class="img-rounded" src="/stockmanagement/assets/user2-160x160.jpg">`

Also when external js path is given in  angular-cli Scripts below error occurs.

![image](https://user-images.githubusercontent.com/22589628/41809175-627e3f3c-7706-11e8-9875-9ccac2159c5d.png)

Below is my public folder image for your reference.
![image](https://user-images.githubusercontent.com/22589628/41809206-2f1fc664-7707-11e8-8c73-58da3dfedae3.png)

Thanks

**Comment by toni-rmc** [comment]
Have you named the route and set `<base href="">` tag?

**Comment by umeshka** [comment]
Hi Toni,
sorry for delay in reply, just now saw your comment's.
Yes i have named the router & base href set as <base href="/">, i will remove the slash and confirm you.
Thanks and Regards,
Umesh

**Comment by toni-rmc** [comment]
You don't have to remove slash that was just an example, your base href path should point to your Angular app, something like `<base href="{{ route('your_app_name', [], false) }}/">`, where `your_app_name` is the name you gave to your route pointing to the Angular app.
Read documentation.
