### ISSUE TITLE
Help Required 

### ISSUE THREAD

**Issue by amboli** [toni-rmc/laravel-angular-integration#13]
Hi Toni,

Currently i am working on Angular 5 ^ version and in that ng-eject is deprecated.  Can you help me to run this project with angular 5^. Early response is highly appreciated.

Thanks,
Ajai.

**Comment by toni-rmc** [comment]
Angular 5 eject is not deprecated, it is at the moment disabled in Angular 6 but it will be enabled in future versions, based on from I have read.
Make sure you don't have version 6 installed instead.
