### ISSUE TITLE
unable to include  angular2-multiselect-dropdown

### ISSUE THREAD

**Issue by Rajan-corient** [toni-rmc/laravel-angular-integration#2]
Hi Toni,
Thanks for the reply.

I also tried as per the instruction you have given for including angular2-multiselect-dropdown, still i am unable to include angular2-multiselect-dropdown and other external libraries & resources.
although i am not getting any error in browser console and in cmd

![cmd](https://user-images.githubusercontent.com/31067215/29363549-0e04f916-82ae-11e7-89ba-a2ba5ef2b271.png)

my app1.config file is....below in screenshot

![app1 conffig](https://user-images.githubusercontent.com/31067215/29362008-a736b9dc-82a7-11e7-8012-4e10b3508956.jpg)

but if include -->(angular2-multiselect-dropdown) folder in App1 root and import in App1/app.module.ts like this 

![app module](https://user-images.githubusercontent.com/31067215/29362628-62997afa-82aa-11e7-98e5-fde356b19a87.jpg)

and the resulting page is as shown below.......but the default css...  multiselect.component.css in the angular2-multiselect-dropdown folder is not not seems to applied in  resulting page.

![result](https://user-images.githubusercontent.com/31067215/29362786-eca19386-82aa-11e7-84fb-201e5ad48a96.jpg)

Please let me know what wrong i am doing... or is there any other css or bootstrap package i am missing.

it would be more better if you can update and release this project with the external resources inclusion with redme for including other external resources. 

Thanks,
Rajan G

**Comment by toni-rmc** [comment]
send me your app1.config.js

did you edit it "angular_apps/config/app1.config.js" and used "npm run ng-compile" ?

**Comment by Rajan-corient** [comment]
Hi Toni,

yes i did all as per your instruction and
still i am not able to include that multiselect dropdown.

here is my app1.config.js file
[app1.config.txt](https://github.com/toni-rmc/laravel-angular-integration/files/1230316/app1.config.txt)


Thanks,
Rajan G

**Comment by toni-rmc** [comment]
Can you also send file of the component where you use angular dropdown
package?

četvrtak, 17. kolovoza 2017. korisnik Rajan-corient <
notifications@github.com> napisao je:

**Comment by Rajan-corient** [comment]
Hi Toni,
Thanks for the reply.

Below is my component and html file where i am trying to use this dropdown.
[dashboard.component(ts).txt](https://github.com/toni-rmc/laravel-angular-integration/files/1230727/dashboard.component.ts.txt),
[dashboard.component(html).txt](https://github.com/toni-rmc/laravel-angular-integration/files/1230729/dashboard.component.html.txt)

and here is my App1/app.module.ts file. 
[app.module(ts).txt](https://github.com/toni-rmc/laravel-angular-integration/files/1230736/app.module.ts.txt)


Thanks & Regards,
Rajan G

**Comment by toni-rmc** [comment]
You have an error in your template html, not related to this issue but you should fix it anyways.

Your **dashboard.component.html** should not have `html`, `head` and `body` tags.

Component template is child of the parent page that initializes Angular and that parent page has those tags.

So when you use `html`, `head`, `body` within component template your page source looks like this:

    <html>
      <head></head>
      <body>
              <angular_selector>
                          // This is where components are loaded.

                         // WRONG! Now you have HTML, HEAD and BODY tags again.
                        <html>
                           <head></head>
                           <body>Component data</body>
                        </html>
              </angular_selector>
      <body>
    </html>

Inline `style` tags are OK.

If you want to include jQuery  or Bootstrap you should not do it using script tags in the template, instead do it in the top level page.

Here is your template with fixed markup:

[dashboard.component.html.txt](https://github.com/toni-rmc/laravel-angular-integration/files/1232271/dashboard.component.html.txt)

This is not causing the issue with `angular2-multiselect-dropdown` to be clear, but just to let you know.

Also small error in **dashboard.component.ts** line #7. It should be `templateUrl:'./dashboard.component.html',`

not

`templateUrl:'./dashboard.Component.html',`

**Comment by toni-rmc** [comment]
Following my own instruction I have implemented `angular2-multiselect-dropdown`.

Here are the screenshots:

![dashboard](https://user-images.githubusercontent.com/1151177/29443625-88ba2a9c-83d9-11e7-878c-985f622d6c58.jpg)

![dashboard2](https://user-images.githubusercontent.com/1151177/29443660-c04ee3b2-83d9-11e7-871e-9b37bc9bb044.jpg)

As you can see there is no issue with the implementation or CSS, your error must be elsewhere.

To track it open Chrome browser and open a console in it, load app and see what errors are you getting in the console.

**Comment by Rajan-corient** [comment]
Hi Toni,
Thanks for the help,

 its started working fine . Pls find screen shot below.

![image](https://user-images.githubusercontent.com/31067215/29458202-949582d2-843b-11e7-90e7-519556680adb.png).


Thanks & Regard,
Rajan G

**Comment by toni-rmc** [comment]
In the next commit adding external libraries will be addressed, and tools for automating the process will be provided.
