### ISSUE TITLE
@ng-idle implementation

### ISSUE THREAD

**Issue by umeshka** [toni-rmc/laravel-angular-integration#4]
Hi Tony,
I am trying to implement Auto logoff feature, but finding it difficult to implement. Can you please let me know where i am doing wrong.

app1.config.js

![image](https://user-images.githubusercontent.com/22589628/30112270-5cb8a360-932e-11e7-8245-4ab512c5adb5.png)

app.module.ts.

![image](https://user-images.githubusercontent.com/22589628/30112323-9148d424-932e-11e7-9bcb-2557591f2d7a.png)

Auto Logoff Example Link.
https://hackedbychinese.github.io/ng2-idle/

Thanks and Regards,
Umesh B. Katakdhond

**Comment by toni-rmc** [comment]
Did you copy libraries folders from `node-modules` to `public/Ng`, `@ng-idle`, `moment` and `angular2-moment`?

Try to change in `map`:

    'angular2-moment': 'npm:angular2-moment/index.js'

to

    'angular2-moment': 'npm:angular2-moment'

And in `packages` try to change

     'angular2-moment': { main: './angular2-moment/index.js', defaultExtension: 'js'  },

to

    'angular2-moment': { main: './index.js', defaultExtension: 'js'  },

Also this in `packages`

    'moment' : {main: './angular2-moment/moment.module.js', defaultExtension: 'js'},

to

    'moment' : {main: './moment.js', defaultExtension: 'js'},

and add this to `map` also

    'moment': 'npm:angular2-moment'

or

    'moment': 'npm:moment'

Did you run

    npm install moment --save
?

**Comment by umeshka** [comment]
Hi Tony,

Thanks for the reply. I will check and let you know the status.

 Also i just wanted to to know how we can integrate AdminLTE Dashboard. Because i have used it and when i click on AdminLTE Menu the entire page is getting reload.

Can you please help on this.

Thanks and Regards,
Umesh B. K

**Comment by umeshka** [comment]
Sorry, forgot to attach images.

![image](https://user-images.githubusercontent.com/22589628/30213313-1b4f4f3e-94c6-11e7-9143-6974c9e45f59.png)

![image](https://user-images.githubusercontent.com/22589628/30213322-211d8dc2-94c6-11e7-8e62-6db069537ebc.png)

**Comment by umeshka** [comment]
Below script is called everytime from Laravel Master Blade.

 <script>
System.import('/main.App1.js').catch(function(err){ console.error(err); });
</script>

**Comment by toni-rmc** [comment]
I have never worked with AdminLTE Dashboard.

I'm guessing you have to define proper Angular route, but I can't tell you more.
Best for you to contact author of that project.

Maybe try this?

https://github.com/TwanoO67/ngx-admin-lte

Anyway so far this project is concerned if you have proper library directories deployed in `public/Ng` rest is just SystemJS configuration.
That depends on each external package individually so search for documentation on the internet for each library you would like to integrate.

Closing this issue since is not really an issue.
