### ISSUE TITLE
Help Required to Use Laravel Logout with Angular 2

### ISSUE THREAD

**Issue by umeshka** [toni-rmc/laravel-angular-integration#5]
Hi Toni,

I have implemented AdminLTE with your package and it's working fine.
But need help for Logout (Have used Laravel Auth). Following is the code.

**starter-header.component.html**
![image](https://user-images.githubusercontent.com/22589628/30437573-92c4d7bc-998c-11e7-812d-2b31178ee84e.png)

starter-header.component.ts
![image](https://user-images.githubusercontent.com/22589628/30437636-b8554124-998c-11e7-9bc4-dd8e94e958d7.png)

http.service.ts
![image](https://user-images.githubusercontent.com/22589628/30437677-cdca5b34-998c-11e7-9079-2be7415c2819.png)

LoginController.php
![image](https://user-images.githubusercontent.com/22589628/30437701-e334fb78-998c-11e7-8b06-25b728c94700.png)

Current Result is.
![image](https://user-images.githubusercontent.com/22589628/30437760-0d55416a-998d-11e7-81a0-66e226317d0f.png)

Expected Result -> when click on Sing out button form should get redirected to Login Page as per below image

![image](https://user-images.githubusercontent.com/22589628/30437863-58944626-998d-11e7-997e-e03a3c7131d8.png)

**Comment by toni-rmc** [comment]
First you need to uncomment first parameter in subscribe() method.

LoginController.php needs to just return data indicating successful logout and not perform redirect itself.

You redirect on Angular side.
You can do that in callback you pass as the first parameter to subscribe using `this.router.navigate(['<aliasInRouteConfig>']);`.

Read documentation about Angular redirects.
