### ISSUE TITLE
Help Required to Use ui-grid with this package

### ISSUE THREAD

**Issue by Rajan-corient** [toni-rmc/laravel-angular-integration#6]
Hi Toni,

Can you please give example on how to use UI Grid, Or else suggest some good Data grid compare to UI Grid.

Thanks and Regards,
Rajan G.

**Comment by toni-rmc** [comment]
From what I read in their documentation it depends on AngularJS, not sure is it working with Angular 2 and above.

Sorry I don't have any recommendation for data Grids.
