### ISSUE TITLE
Can't bind to 'ngclass'

### ISSUE THREAD

**Issue by umeshka** [toni-rmc/laravel-angular-integration#9]
If i use npm run ng-compile-prod following error happend.
![image](https://user-images.githubusercontent.com/22589628/40360660-73577fc0-5de4-11e8-94a3-a75a06bc2c93.png)
But if i use npm run ng-compile the everything work fine.
Also i takes time to load. due to scripts.

Please help to reslove this issue.

Thanks and Regards,
Umesh B. K

**Comment by toni-rmc** [comment]
Try to move to latest version of this project and also to Angular 5.
